package com.im.service.common;

public enum DataType {
	NULL,
	BLANK,
	NUMERIC,
	ALPHABET,
	ALPHABET_UPPERCASE,
	ALPHABET_LOWERCASE,
	ALPHA_NUMERIC,
	ALPHA_NUMERIC_UPPERCASE,
	ALPHA_NUMERIC_LOWERCASE,
	SPECIAL_CHARS,
	UNASSIGNED,
	EMAIL
}
